HealthbridgeApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HealthbridgeApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HealthbridgeApp/Controllers/InvoiceController.cs
using HealthbridgeApi.Dto;
using HealthbridgeApiHelper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HealthbridgeApp.Controllers
{
    public class InvoiceController : Controller
    {
        private readonly IInvoiceRepository _repo;

        public InvoiceController(IInvoiceRepository repo)
        {
            _repo = repo;
        }
        // GET: Invoice
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public JsonResult GetInvoices()
        {
            var response = _repo.GetInvoices();
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        // GET: Invoice/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        [HttpGet]
        public JsonResult GetInvoiceById(int id)
        {
            var response = _repo.GetInvoiceById(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult createInvoice(InvoiceForCaptureDto d)
        {
            var response = _repo.AddInvoice(d);
            return Json(response, JsonRequestBehavior.AllowGet); ;
        }

        [HttpPost]
        public JsonResult updateInvoice(InvoiceForCaptureDto data) {
            var response = _repo.UpdateInvoice(data);
            return Json(response, JsonRequestBehavior.AllowGet); ;
        }

        [HttpPost]
        public JsonResult DeleteInvoiceItem(InvoiceLineDto lineDto)
        {
            var response = _repo.DeleteInvoiceItem(lineDto.InvoiceLineId);
            return Json(response, JsonRequestBehavior.AllowGet); ;
        }
        public ActionResult Capture()
        {
            return View();
        }
    }
}

HealthbridgeApp/Controllers/PatientController.cs
using HealthbridgeApi.Dto;
using HealthbridgeApiHelper;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HealthbridgeApp.Controllers
{
    public class PatientController : Controller
    {
        private readonly IPatientRepository _patientRepository;

        public PatientController(IPatientRepository patientRepository) {

            _patientRepository = patientRepository;
        }
        // GET: Patient
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetPatientList() {
            var response = _patientRepository.GetPatients();
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Register(PatientDto data)
        {
            var response = _patientRepository.Register(data);
            return Json(response,JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Edit()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetPatientById(int? id) {
            if (id.HasValue && id.Value > 0) //Check Id has value or null
            {
                var patient = _patientRepository.GetPatientById(id); 
                if (patient != null)
                {
                    return Json(patient, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { Status = "Failure" }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Detail() {
            return View();
        }
        [HttpPost]
        public JsonResult UpdatePatient(PatientDto dtoToupdate)
        {
            var response = _patientRepository.updatePatient(dtoToupdate);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult DeletePatient(PatientDto data)
        {
            var response = _patientRepository.DeletePatient(data);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
    }
}

HealthbridgeApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HealthbridgeApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HealthbridgeApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

HealthbridgeApp/Views/Invoice/Capture.cshtml
@{
    ViewBag.Title = "Capture";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Capture</h2>

<link href="https://cdnjs.cloudflare.com/ajax/libs/angularjs-toaster/3.0.0/toaster.min.css" rel="stylesheet" />
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.0/angular.min.js"></script>
<script src="https://code.angularjs.org/1.2.0/angular-animate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angularjs-toaster/3.0.0/toaster.min.js"></script>

<toaster-container></toaster-container>

<div ng-controller="myController">
    <button style="color:#808080" ng-click="pop()">Show a Toaster</button>
</div>

<script>
    angular.module('main', ['toaster', 'ngAnimate'])
    .controller('myController', function($scope, toaster) {
        $scope.pop = function(){
            toaster.pop('info', "title", "text");
        };
    });
</script>
<style>
    body {
        color: white;
        background: black;
    }
      .table-hover > tbody > tr:hover {
    background-color: #7d5a5a;
}
              .btn-primary {
    color: #fff;
    background-color: #2f2f30;
    border-color: #e8e8e8;
}
      
element.style {
}
.btn-primary:active:hover, .btn-primary.active:hover, .open > .dropdown-toggle.btn-primary:hover, .btn-primary:active:focus, .btn-primary.active:focus, .open > .dropdown-toggle.btn-primary:focus, .btn-primary:active.focus, .btn-primary.active.focus, .open > .dropdown-toggle.btn-primary.focus {
    color: #fff;
    background-color: #878e90;
    border-color: #cccccc;
}
</style>

HealthbridgeApp/Views/Invoice/Details.cshtml
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h2>Patients invoice detail</h2>

<fieldset>
    <legend > </legend>
    <div ng-app="app" ng-controller="InvoiceCtr">
        <div class="table-responsive">

            <table class="table table-hover table-bordered">

                <tbody>
                    <tr>
                        <td>Invoice Date</td>
                        <td ng-show="!EditMode && !currentInvoiceId==0">{{invoice.InvoiceDateTime}}</td>
                        <td ng-show="EditMode || currentInvoiceId==0">
                            <input type="text" name="InvoiceDateTime" class="form-control" ng-model="invoice.InvoiceDateTime" required ng-maxlength="50">
                        </td>
                    </tr>
                    <tr ng-show="currentInvoiceId > 0">
                        <td>
                            Patient
                        </td>
                        <td>
                            {{invoice.FirstName}} {{invoice.LastName}}
                        </td>
                    </tr>

                    <tr ng-show="currentInvoiceId===0">
                        <td>
                            Patient Number
                        </td>
                        <td>
                            <input type="text" name="InvoiceDateTime" class="form-control" ng-model="invoice.PatientId" required ng-maxlength="50">
                        </td>
                    </tr>

                </tbody>
            </table>


            <table class="table table-hover  table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Qty</th>
                        <th scope="col">Code</th>
                        <th scope="col">Description</th>
                        <th scope="col">Total</th>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="item in invoice.InvoiceLine">
                        <td ng-show="!EditMode && !item.InvoiceLineId==0">{{item.Qty}}</td>
                        <td ng-show="EditMode || item.InvoiceLineId==0">
                            <input type="text" name="qty" class="form-control" ng-model="item.Qty" required ng-maxlength="50">
                        </td>

                        <td ng-show="!EditMode && !item.InvoiceLineId==0">{{item.Code}}</td>
                        <td ng-show="EditMode || item.InvoiceLineId==0">
                            <input type="text" name="code" class="form-control" ng-model="item.Code" required ng-maxlength="50">
                        </td>

                        <td ng-show="!EditMode && !item.InvoiceLineId==0">{{item.Description}}</td>
                        <td ng-show="EditMode || item.InvoiceLineId==0">
                            <input type="text" name="discription" class="form-control" ng-model="item.Description" required ng-maxlength="50">
                        </td>

                        <td ng-show="!EditMode && !item.InvoiceLineId==0">{{item.LineTotal}}</td>
                        <td ng-show="EditMode || item.InvoiceLineId==0">
                            <input type="text" name="total" class="form-control" ng-model="item.LineTotal" ng-pattern="/^[0-9]+(\.[0-9]{1,2})?$/" step="0.01" required>
                        </td>
                        <td class="btn btn-danger"><button ng-click="DeleteItem(item)">x</button></td>
                    </tr>

                </tbody>
                <tfoot>
                    <tr ng-show="invoice.InvoiceLine.length" style="font-weight:bold">
                        <td>{{getTotalQty()}}</td>
                        <td></td>
                        <td></td>
                        <td>{{getTotal()}}</td>
                        <td></td>

                    </tr>
                    <tr>
                        <td><button class="btn-primary" ng-click="AddLineItem()">Add Item</button></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>

                    </tr>
                </tfoot>
            </table>
            <br />
            <table class="table table-hover table-bordered">

                <tbody>
                    <tr>
                        <td><button class="btn btn-primary" ng-click="AddLineNewInvoice(invoice)">New Invoice</button></td>
                        <td><button class=" btn btn-primary" ng-click="EditLineItem(invoice)">Update Line Items</button></td>
                        <td><button class="btn btn-primary" ng-click="cancel()">Cancel</button></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <button class="btn btn-success" ng-click="saveChanges(invoice)" ng-disabled="modeType === ''">Save Changes</button>

    </div>
</fieldset>
<toaster-container></toaster-container>

<script src="~/Scripts/angular.js"></script>
<link href="~/Content/toaster.min.css" rel="stylesheet" />
<script src="~/Scripts/angular.js"></script>

<script src="~/Scripts/toaster.min.js"></script>
<script src="~/Scripts/angular-animate.min.js"></script>
<script src="~/Scripts/toaster.min.js"></script>


<script src="~/Scripts/App/Controllers/InvoiceDetails.js"></script>



<script>
//    (function () {
//    //Module
//    var app = angular.module('app', []);
//    // Controller
//    app.controller('InvoiceCtr', function ($scope) {

//         $scope.invoice = {
//            PatientId: 14,
//            InvoiceDateTime: '2019-11-25',
//            FirstName: 'Terro',
//            LastName: 'Marvel',
//            InvoiceLine: [
//                {
//                    InvoiceLineId: 5,
//                    InvoiceId: 9,
//                    Qty: 1.0,
//                    Code: 'AA4',
//                    Description: 'Sterilizer',
//                    LineTotal: 20.0000
//                },
//                {
//                    InvoiceLineId: 6,
//                    InvoiceId: 9,
//                    Qty: 1.0,
//                    Code: 'AB4',
//                    Description: 'morph',
//                    LineTotal: 50.0000
//                }
//            ]
//        };
//    });

//})();
</script>
<style>
    body {
    color: white;
    background: black;
}
    legend {
    display: block;
    width: 100%;
    padding: 0;
    margin-bottom: 20px;
    font-size: 21px;
    line-height: inherit;
    color: #ffffff !important;
    border: 0;
    border-bottom: 1px solid #e5e5e5;
}
      .table-hover > tbody > tr:hover {
    background-color: #7d5a5a;
}
      .btn-primary {
    color: #fff;
    background-color: #2f2f30;
    border-color: #e8e8e8;
}
      
element.style {
}
.btn-primary:active:hover, .btn-primary.active:hover, .open > .dropdown-toggle.btn-primary:hover, .btn-primary:active:focus, .btn-primary.active:focus, .open > .dropdown-toggle.btn-primary:focus, .btn-primary:active.focus, .btn-primary.active.focus, .open > .dropdown-toggle.btn-primary.focus {
    color: #fff;
    background-color: #878e90;
    border-color: #cccccc;
}
.btn-danger {
    color: #fa1313;
    background-color: #8c8686;
}
.btn-primary:hover {
    color: #fff;
    background-color: #7e868d;
    border-color: #ececec;
}

</style>

HealthbridgeApp/Views/Invoice/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <h2>All patients invoice list</h2>
<fieldset>
    <legend> </legend>
    <div ng-app="app" ng-controller="InvoiceCtr">
        <div class="table-responsive">
            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Invoice Date</th>
                        <th scope="col">Patient</th>
                        <th scope="col">Invoice Total</th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="invoice in InvoiceList" ng-click="RedirectToDetails(invoice.InvoiceId)" >
                        <td >{{invoice.InvoiceDateTime}}</td>
                        <td>{{invoice.FirstName}} {{invoice.LastName}}</td>
                        <td>{{invoice.InvoiceTotal}}</td>
                    </tr>
                </tbody>
            </table>
            <div><button ng-show="invoice ===null" class="btn-primary" ng-click="RedirectToDetails(0)">Add Patient Invoive</button></div>
        </div>
    </div>
</fieldset>
<script src="~/Scripts/angular.js"></script>
<script src="~/Scripts/App/Controllers/Invoice.js"></script>
<style>
    body {
        color: white;
        background: black;
    }
     legend {
    display: block;
    width: 100%;
    padding: 0;
    margin-bottom: 20px;
    font-size: 21px;
    line-height: inherit;
    color: #ffffff !important;
    border: 0;
    border-bottom: 1px solid #e5e5e5;
}
   .table-hover > tbody > tr:hover {
    background-color: #7d5a5a;
}
         .btn-primary {
    color: #fff;
    background-color: #2f2f30;
    border-color: #e8e8e8;
}
      
element.style {
}
.btn-primary:active:hover, .btn-primary.active:hover, .open > .dropdown-toggle.btn-primary:hover, .btn-primary:active:focus, .btn-primary.active:focus, .open > .dropdown-toggle.btn-primary:focus, .btn-primary:active.focus, .btn-primary.active.focus, .open > .dropdown-toggle.btn-primary.focus {
    color: #fff;
    background-color: #878e90;
    border-color: #cccccc;
}
.btn-danger {
    color: #fa1313;
    background-color: #8c8686;
}
.btn-primary:hover {
    color: #fff;
    background-color: #545e66;
    border-color: #abc1d3;
}
</style>

HealthbridgeApp/Views/Patient/Detail.cshtml
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Patient Details</h2>
<div ng-app="app" ng-controller="PatientCtr">
    <table class="table table-bordered table-hover table-responsive">
        <tr>
            <td><b>Patient Number:</b></td>
            <td>{{PatientId}}</td>
        </tr>
        <tr>
            <td><b>First Name:</b></td>
            <td>{{FirstName}}</td>
        </tr>
        <tr>
            <td><b>Last Name:</b></td>
            <td>{{LastName}}</td>
        </tr>
        <tr>
            <td><b>ID Number:</b></td>
            <td>{{IdNumber}}</td>
        </tr>
        
    </table>
    <p class="btn btn-primary"> @Html.ActionLink("Back to List", "Index", null, new { style = "color:white" })</p>
</div>
<script src="~/Scripts/angular.js"></script>
<script src="~/Scripts/App/PatientDetail.js"></script>
<style>
    body {
        color: white;
        background: black;
    }
    h2{
        color:#ffffff;
    }
      .table-hover > tbody > tr:hover {
    background-color: #7d5a5a;
}
           .btn-primary {
    color: #fff;
    background-color: #2f2f30;
    border-color: #e8e8e8;
}
      
element.style {
}
.btn-primary:active:hover, .btn-primary.active:hover, .open > .dropdown-toggle.btn-primary:hover, .btn-primary:active:focus, .btn-primary.active:focus, .open > .dropdown-toggle.btn-primary:focus, .btn-primary:active.focus, .btn-primary.active.focus, .open > .dropdown-toggle.btn-primary.focus {
    color: #fff;
    background-color: #878e90;
    border-color: #cccccc;
}
.btn-danger {
    color: #fa1313;
    background-color: #8c8686;
}

</style>

HealthbridgeApp/Views/Patient/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align:center">Edit Patient Information</h2>
<br>
<hr />
<div ng-app="app" ng-controller="PatientCtr">
    <form name="EditForm" novalidate>
        <table class="table table-bordered table-responsive">

            <tr>
                <td>First Name</td>
                <td class="form-group">
                    <input class="form-group" type="text" ng-model="FirstName" name="eFirstName" required autofocus />
                    <span class="error" ng-show="(EditForm.FirstName.$dirty || submitted) && EditForm.FirstName.$error.required">First Name Is Required</span>
                </td>
            </tr>
            <tr>
                <td>Last Name</td>
                <td>
                    <input class="textbox" type="text" ng-model="LastName" name="eLastName" required autofocus />
                    <span class="error" ng-show="(EditForm.LastName.$dirty || submitted) && EditForm.LastName.$error.required">Last Name Is Required</span>
                </td>
            </tr>
            <tr>
                <td>ID Number</td>
                <td>
                    <input class="textbox" type="text" ng-model="IdNumber" name="eIdNumber" required autofocus />
                    <span class="error" ng-show="(EditForm.IdNumber.$dirty || submitted) && EditForm.IdNumber.$error.required">ID Number Is Required</span>
                </td>
            </tr>
        </table>
        <input type="submit" class="btn btn-success" ng-click="UpdatePatient()" value="Update" />
        <p class="btn btn-primary">@Html.ActionLink("Back to List", "Index", null, new { style = "color:white" })</p>
    </form>
    
</div>
<script src="~/Scripts/angular.js"></script>
<script src="~/Scripts/App/PatientDetail.js"></script>
<style>
    body {
        color: white;
        background: black;
    }
    h2 {
    color: #ffffff;
}
       .table-hover > tbody > tr:hover {
    background-color: #7d5a5a;
}
             .btn-primary {
    color: #fff;
    background-color: #2f2f30;
    border-color: #e8e8e8;
}
      
element.style {
}
.btn-primary:active:hover, .btn-primary.active:hover, .open > .dropdown-toggle.btn-primary:hover, .btn-primary:active:focus, .btn-primary.active:focus, .open > .dropdown-toggle.btn-primary:focus, .btn-primary:active.focus, .btn-primary.active.focus, .open > .dropdown-toggle.btn-primary.focus {
    color: #fff;
    background-color: #878e90;
    border-color: #cccccc;
}
input, select, textarea {
    max-width: 280px;
    color: black;
}
</style>

HealthbridgeApp/Views/Patient/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h2>Patient List </h2>
    <fieldset>
        <legend></legend>
        <button class="btn btn-primary" onclick="location.href='@Url.Action("Register", "Patient")'">Register</button>
    </fieldset>
<br />
<fieldset>
    <legend></legend>
    <div ng-app="app" ng-controller="PatientController">
        <form>
            <div class="table-responsive form-group"      >
                <input type='text' class="form-control" ng-model='searchText' placeholder="Search patient " />
                <br />
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">First Name</th>
                            <th scope="col">Last Name</th>
                            <th scope="col">ID Number</th>
                            <th></th>

                        </tr>
                    </thead>
                    <tbody>
                        <tr ng-repeat="patient in PatientList | filter:serchText">
                            <td>{{patient.FirstName}}</td>
                            <td>{{patient.LastName}}</td>
                            <td>{{patient.IdNumber}}</td>
                            <td>
                                <button class="btn btn-info" ng-click="RedirectToEdit(patient)">Edit</button>|
                                <button class="btn btn-default" ng-click="RedirectToDetails(patient)">Details</button> |
                                <button class="btn btn-danger" ng-click="DeletePatient(patient)">Delete</button>  |
                            </td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </form>
    </div>
</fieldset>
<script src="~/Scripts/angular.js"></script>
<script src="~/Scripts/App/Patient.js"></script>
<style>
    body {
        color: white;
        background: black;
    }
        legend {
    display: block;
    width: 100%;
    padding: 0;
    margin-bottom: 20px;
    font-size: 21px;
    line-height: inherit;
    color: #ffffff !important;
    border: 0;
    border-bottom: 1px solid #e5e5e5;
}
        .table-hover > tbody > tr:hover {
    background-color: #7d5a5a;
}
              .btn-primary {
    color: #fff;
    background-color: #2f2f30;
    border-color: #e8e8e8;
}
      
element.style {
}
.btn-primary:active:hover, .btn-primary.active:hover, .open > .dropdown-toggle.btn-primary:hover, .btn-primary:active:focus, .btn-primary.active:focus, .open > .dropdown-toggle.btn-primary:focus, .btn-primary:active.focus, .btn-primary.active.focus, .open > .dropdown-toggle.btn-primary.focus {
    color: #fff;
    background-color: #878e90;
    border-color: #cccccc;
}
</style>

HealthbridgeApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/toaster.min.css" rel="stylesheet" />
    <script src="~/Scripts/angular.js"></script>

    <script src="~/Scripts/toaster.min.js"></script>
    <script src="~/Scripts/angular-animate.min.js"></script>
    <script src="~/Scripts/toaster.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HealthBridge", "Index", "Patient", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Registration", "Register", "Patient")</li>
                    <li>@Html.ActionLink("Patient Invoice", "Index", "Invoice")</li>
                </ul>
            </div>
        </div>
    </div>
    <toaster-container toaster-options="{'time-out': 3000, 'position-class': 'toast-bottom-right', 'close-button':true, 'animation-class': 'toast-bottom-left'}"></toaster-container>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Health Bridge</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
<style>
    body {
        color: white;
        background: black;
    }
      tr:hover{
        background-color: #808080;
    }
</style>